# -*- coding:ascii -*-
from mako import runtime, filters, cache
UNDEFINED = runtime.UNDEFINED
__M_dict_builtin = dict
__M_locals_builtin = locals
_magic_number = 10
_modified_time = 1428112764.882606
_enable_loop = True
_template_filename = '/Users/Dennis/Developer/Python/chf/homepage/templates/rentals.return_rental.html'
_template_uri = 'rentals.return_rental.html'
_source_encoding = 'ascii'
import os, os.path, re
_exports = ['content']


def _mako_get_namespace(context, name):
    try:
        return context.namespaces[(__name__, name)]
    except KeyError:
        _mako_generate_namespaces(context)
        return context.namespaces[(__name__, name)]
def _mako_generate_namespaces(context):
    pass
def _mako_inherit(template, context):
    _mako_generate_namespaces(context)
    return runtime._inherit_from(context, 'base.htm', _template_uri)
def render_body(context,**pageargs):
    __M_caller = context.caller_stack._push_frame()
    try:
        __M_locals = __M_dict_builtin(pageargs=pageargs)
        user = context.get('user', UNDEFINED)
        def content():
            return render_content(context._locals(__M_locals))
        status = context.get('status', UNDEFINED)
        lf = context.get('lf', UNDEFINED)
        rental = context.get('rental', UNDEFINED)
        delta = context.get('delta', UNDEFINED)
        agent = context.get('agent', UNDEFINED)
        new_return = context.get('new_return', UNDEFINED)
        returned_item = context.get('returned_item', UNDEFINED)
        __M_writer = context.writer()
        __M_writer('\r\n\r\n')
        if 'parent' not in context._data or not hasattr(context._data['parent'], 'content'):
            context['self'].content(**pageargs)
        

        return ''
    finally:
        context.caller_stack._pop_frame()


def render_content(context,**pageargs):
    __M_caller = context.caller_stack._push_frame()
    try:
        user = context.get('user', UNDEFINED)
        def content():
            return render_content(context)
        status = context.get('status', UNDEFINED)
        lf = context.get('lf', UNDEFINED)
        rental = context.get('rental', UNDEFINED)
        delta = context.get('delta', UNDEFINED)
        agent = context.get('agent', UNDEFINED)
        new_return = context.get('new_return', UNDEFINED)
        returned_item = context.get('returned_item', UNDEFINED)
        __M_writer = context.writer()
        __M_writer('\r\n\t<h1> ')
        __M_writer(str(status))
        __M_writer(' </h1>\r\n\r\n')
        if delta > 0:
            __M_writer('\t\t<h4> It is actually ')
            __M_writer(str(delta))
            __M_writer(' days late to be exact </h4>\r\n\t\t<p> There will be a small fee involved. The fees are generated by taking the standard rental price of an item and dividing it by seven, which gives a daily fee that is added onto the total late fee each day that it is overdue</p>\r\n\t\t<h4> The total late fee for this item is: ')
            __M_writer(str(lf.amount))
            __M_writer('</h4>\r\n')
        __M_writer('\r\n\t</br></br>\r\n\r\n\t<button id="damages" class="btn btn-primary" data-userid="')
        __M_writer(str(user.id))
        __M_writer('" data-agentid="')
        __M_writer(str(agent.id))
        __M_writer('" data-returnid="')
        __M_writer(str(new_return.id))
        __M_writer('" data-rentalid="')
        __M_writer(str(rental.id))
        __M_writer('" data-itemid="')
        __M_writer(str(returned_item.id))
        __M_writer('">Is there damage?</button>\r\n\r\n\t</br></br>\r\n\r\n\t<a class="btn btn-success" href="/homepage/rentals.return_item/')
        __M_writer(str( user.id ))
        __M_writer('/')
        __M_writer(str( agent.id ))
        __M_writer('/">OK Done</a>\r\n\r\n')
        return ''
    finally:
        context.caller_stack._pop_frame()


"""
__M_BEGIN_METADATA
{"uri": "rentals.return_rental.html", "source_encoding": "ascii", "line_map": {"66": 3, "67": 4, "68": 4, "69": 6, "70": 7, "71": 7, "72": 7, "73": 9, "74": 9, "75": 11, "76": 14, "77": 14, "78": 14, "79": 14, "80": 14, "81": 14, "82": 14, "83": 14, "84": 14, "85": 14, "86": 18, "87": 18, "88": 18, "89": 18, "27": 0, "95": 89, "42": 1, "52": 3}, "filename": "/Users/Dennis/Developer/Python/chf/homepage/templates/rentals.return_rental.html"}
__M_END_METADATA
"""
